<a href="https://colab.research.google.com/github/davidr1008/Day1/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementing Numpy using Python Programming 
 

In [1]:
#Importing Libraries
import numpy as np
a = [1,2,3,4] #list
arr1 = np.array(a)
print(arr1)
b = [[1,2,3,4],[5,6,7,8]] #list2
arr2 = np.array(b)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
import sys

s = np.arange(10000)
print("Size of each element of numpy array in bytes",s.itemsize)
print("Size of whole array in bytes:",s.size*s.itemsize)

Size of each element of numpy array in bytes 8
Size of whole array in bytes: 80000


In [3]:
import numpy as np
import time

a = np.arange(10000)
b = np.arange(10000)

start =time.time() #mark the start time

ab = [(a*b) for a,b in zip(a,b)]
end =time.time() #mark the end time
print("Total time taken:", end - start)

Total time taken: 0.007393598556518555


In [4]:
import numpy as np
arr3 = np.array([[1,2,3,4],[5,6,7,8]],ndmin =2) #2D np array
print(arr3)


[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr4 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

int64
2
(2, 4)
8


In [6]:

zero1 = np.zeros((2,2))
print(zero1)


[[0. 0.]
 [0. 0.]]


In [7]:
c = np.arange(3,10,2)
print(type(c))

<class 'numpy.ndarray'>


In [8]:
a = [1,2,3,4,5] 
b = np.array(a)
print(b)

[1 2 3 4 5]


In [9]:
b[2]
b[4]

5

In [10]:
b[-3]

3

In [11]:
b[0:2]

array([1, 2])

In [12]:
b[0:4]

array([1, 2, 3, 4])

In [13]:
b[2]

3

In [14]:
print(b)

[1 2 3 4 5]


In [15]:
print(b[3, ])

4


In [16]:
print(b[3: ])


[4 5]


In [17]:
print(b[5: ])

[]


In [18]:
print(b[:4])

[1 2 3 4]


In [19]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
print(c[0])

[1 2 3 4 5]


In [21]:
print(c[0][3])

4


Pandas Library Implementation 


In [24]:
#pandas is used for handling data and dataset 
import pandas as pd
dataset = pd.read_csv("/content/student details.csv")

In [25]:
dataset.head(5)


ID  Name Year Department Section
0   1  Phil  4th       AERO       A
1   2   Stu  1st         IT       A
2   3   Dou  2nd        CSE       B
3   4  Alan  5th       MECH       B
4   5  Chow  1st      CIVIL       C

In [26]:
dataset.tail(3)

ID  Name Year Department Section
2   3   Dou  2nd        CSE       B
3   4  Alan  5th       MECH       B
4   5  Chow  1st      CIVIL       C

In [27]:
dataset.shape

(5, 5)

In [28]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ID          5 non-null      int64 
 1   Name        5 non-null      object
 2   Year        5 non-null      object
 3   Department  5 non-null      object
 4   Section     5 non-null      object
dtypes: int64(1), object(4)
memory usage: 328.0+ bytes


In [29]:
dataset1 = pd.read_html("https://en.wikipedia.org/wiki/Data_science")[0] 
dataset1.head()


0
0                                Part of a series on
1                    Machine learningand data mining
2  Problems Classification Clustering Regression ...
3  Supervised learning.mw-parser-output .nobold{f...
4  Clustering BIRCH CURE Hierarchical k-means Exp...

In [30]:
dataset.ID

0    1
1    2
2    3
3    4
4    5
Name: ID, dtype: int64

In [31]:
dataset.Name

0    Phil
1     Stu
2     Dou
3    Alan
4    Chow
Name: Name, dtype: object

In [33]:
dataset[['ID', 'Name', 'Department']]

ID  Name Department
0   1  Phil       AERO
1   2   Stu         IT
2   3   Dou        CSE
3   4  Alan       MECH
4   5  Chow      CIVIL